version: "3.9"
   
services:
  proxy:
    image: "traefik:v2.4"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"


  web-frontend:
    build:
      context: ../webapp
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=PathPrefix(`/`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.services.frontend.loadbalancer.server.port=5000"

  timetable:
    build:
      context: ../timetable
    depends_on:
      - postgres
    environment:
      - PG_USER=postgres
      - PG_PASSWORD=pass123
      - PG_HOST=postgres
      - PG_PORT=5432
      - PG_DATABASE=timetable
      - PYTHONDONTWRITEBYTECODE=1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=PathPrefix(`/appointment`)"
      - "traefik.http.routers.backend.entrypoints=web"
      - "traefik.http.services.backend.loadbalancer.server.port=80"

  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass123
      - POSTGRES_DB=timetable
